# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080

# Spring配置
spring:
  profiles:
    active: dev

  # redis 配置
  redis:
    # 地址
    host: localhost
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password:

ucode:
  code:
    project-dir: ucode-cms-admin

  job:
    enabled: false