# Tomcat
server:
  port: 8080

# Spring
spring:
  application:
    # 应用名称
    name: auto-code
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/park?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

# 日志配置
logging:
  level:
    xin.altitude: info
    org.springframework: warn