# 项目相关配置
ucode:
  cms:
    # 名称
    name: UCodeCms
    # 版本
    version: 1.0.0
    # 版权年份
    copyrightYear: 2021
    # 实例演示开关
    demoEnabled: true
    # 文件路径 示例（ Windows配置D:/cms/uploadPath，Linux配置 /home/cms/uploadPath）
    profile: D:/cms/uploadPath
    # 获取ip地址开关
    addressEnabled: false
    # 验证码类型 math 数组计算 char 字符验证
    captchaType: math
    # 是否需要认证
    authEnabled: false
  # token配置
  token:
    # 令牌自定义标识
    header: Authorization
    # 令牌密钥
    secret: abcdefghijklmnopqrstuvwxyz
    # 令牌有效期（默认30分钟）
    expireTime: 30
  # Swagger配置
  swagger:
    # 是否开启swagger
    enabled: true
    # 请求前缀
    pathMapping: /dev-api

  # 防止XSS攻击
  xss:
    # 过滤开关
    enabled: true
    # 排除链接（多个用逗号分隔）
    excludes: /system/notice
    # 匹配链接
    urlPatterns: /system/*,/monitor/*,/tool/*