# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080

# Spring配置
spring:
  main:
    allow-circular-references: true
  config:
    use-legacy-processing: true
  profiles:
    active: dev

  # redis 配置
  redis:
    # 地址
    host: localhost
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password:

ucode:
  code:
    project-dir: demo-ucode-cms
    package-name: "xin.ucode.front"
    domain:
      add-construction-method: true
